"""create initial tables

Revision ID: 0a9ff20b0518
Revises: 
Create Date: 2026-05-21 13:18:07.089730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9ff20b0518'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_seed_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('total_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('player_level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_seed_players_display_name'), 'leaderboard_seed_players', ['display_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('legal_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('document_version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_type', 'document_version', name='uq_legal_acceptances_user_document_version')
    )
    op.create_index(op.f('ix_legal_acceptances_user_id'), 'legal_acceptances', ['user_id'], unique=False)
    op.create_table('mission_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mission_number', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('best_flight_accuracy_bonus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('best_tank_hit_bonus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('best_score >= 0', name='ck_mission_progress_best_score_min'),
    sa.CheckConstraint('mission_number >= 1', name='ck_mission_progress_mission_number_min'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_number', name='uq_mission_progress_user_mission')
    )
    op.create_index(op.f('ix_mission_progress_user_id'), 'mission_progress', ['user_id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('name_changed_once', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('total_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('player_level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_profiles_display_name'), 'player_profiles', ['display_name'], unique=True)
    op.create_index(op.f('ix_player_profiles_user_id'), 'player_profiles', ['user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_player_profiles_user_id'), table_name='player_profiles')
    op.drop_index(op.f('ix_player_profiles_display_name'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_mission_progress_user_id'), table_name='mission_progress')
    op.drop_table('mission_progress')
    op.drop_index(op.f('ix_legal_acceptances_user_id'), table_name='legal_acceptances')
    op.drop_table('legal_acceptances')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leaderboard_seed_players_display_name'), table_name='leaderboard_seed_players')
    op.drop_table('leaderboard_seed_players')
    # ### end Alembic commands ###
